osx_image: xcode10.1
language: objective-c

script:
  - swift package generate-xcodeproj
  - xcodebuild -scheme ModelGen -sdk macosx -configuration Release -enableCodeCoverage YES test

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
