//
//  User.kt
//  ModelGen
//
//  Generated by [ModelGen]: https://github.com/hebertialmeida/ModelGen
//  Copyright © 2018 ModelGen. All rights reserved.
//

/// Definition of a User
data class User(
    val email: String,
    /**
     yooo
     */
    val id: Int,
    val timezone: String?,
    val fullName: String,
    val createdAt: Date,
    val avatar: Avatar,
    val currentCompanyId: Int,
    val companies: Array<Company>
)
